import {
  ATTR_ALLOW_SLIDE_NEXT,
  ATTR_ALLOW_SLIDE_PREV,
  ATTR_ALLOW_TOUCH_MOVE,
  ATTR_AUTO_HEIGHT,
  ATTR_BREAKPOINTS_BASE,
  ATTR_CENTER_INSUFFICIENT_SLIDES,
  ATTR_CENTERED_SLIDES,
  ATTR_CONTAINER_MODIFIER_CLASS,
  ATTR_CREATE_ELEMENTS,
  ATTR_CSS_MODE,
  ATTR_DIRECTION,
  ATTR_EDGE_SWIPE_DETECTION,
  ATTR_EDGE_SWIPE_THRESHOLD,
  ATTR_EFFECT,
  ATTR_ENABLED,
  ATTR_EVENTS_PREFIX,
  ATTR_FOCUSABLE_ELEMENTS,
  ATTR_FOLLOW_FINGER,
  ATTR_FREE_MODE_ENABLED,
  ATTR_FREE_MODE_STICKY,
  ATTR_SLIDE_FULLY_VISIBLE_CLASS,
  ATTR_GRAB_CURSOR,
  ATTR_HEIGHT,
  ATTR_INIT,
  ATTR_INITIAL_SLIDE,
  ATTR_LAZY_PRELOAD_PREV_NEXT,
  ATTR_LAZY_PRELOADER_CLASS,
  ATTR_LONG_SWIPES,
  ATTR_LONG_SWIPES_MS,
  ATTR_LONG_SWIPES_RATIO,
  ATTR_LOOP,
  ATTR_LOOP_ADD_ADDITIONAL_SLIDES,
  ATTR_LOOP_ADD_BLANK_SLIDES,
  ATTR_LOOP_PREVENTS_SLIDING,
  ATTR_MAX_BACKFACE_HIDDEN_SLIDES,
  ATTR_NESTED,
  ATTR_NO_SWIPING,
  ATTR_NO_SWIPING_CLASS,
  ATTR_NO_SWIPING_SELECTOR,
  ATTR_NORMALIZE_SLIDE_INDEX,
  ATTR_OBSERVE_SLIDE_CHILDREN,
  ATTR_OBSERVE_SLIDE_PARENTS,
  ATTR_OBSERVER,
  ATTR_ONE_WAY_MOVEMENT,
  ATTR_PASSIVE_LISTENERS,
  ATTR_PREVENT_CLICKS,
  ATTR_PREVENT_CLICKS_PROPAGATION,
  ATTR_PREVENT_INTERACTION_ON_TRANSITION,
  ATTR_RESISTANCE,
  ATTR_RESISTANCE_RATIO,
  ATTR_RESIZE_OBSERVER,
  ATTR_REWIND,
  ATTR_ROUND_LENGTHS,
  ATTR_RUN_CALLBACKS_ON_INIT,
  ATTR_SET_WRAPPER_SIZE,
  ATTR_SHORT_SWIPES,
  ATTR_SIMULATE_TOUCH,
  ATTR_SLIDE_ACTIVE_CLASS,
  ATTR_SLIDE_BLANK_CLASS,
  ATTR_SLIDE_CLASS,
  ATTR_SLIDE_NEXT_CLASS,
  ATTR_SLIDE_PREV_CLASS,
  ATTR_SLIDE_TO_CLICKED_SLIDE,
  ATTR_SLIDE_VISIBLE_CLASS,
  ATTR_SLIDES_OFFSET_AFTER,
  ATTR_SLIDES_OFFSET_BEFORE,
  ATTR_SLIDES_PER_GROUP,
  ATTR_SLIDES_PER_GROUP_AUTO,
  ATTR_SLIDES_PER_GROUP_SKIP,
  ATTR_SLIDES_PER_VIEW,
  ATTR_SPACE_BETWEEN,
  ATTR_SPEED,
  ATTR_SWIPE_HANDLER,
  ATTR_SWIPER_ELEMENT_NODE_NAME,
  ATTR_THRESHOLD,
  ATTR_TOUCH_ANGLE,
  ATTR_TOUCH_EVENTS_TARGET,
  ATTR_TOUCH_MOVE_STOP_PROPAGATION,
  ATTR_TOUCH_RATIO,
  ATTR_TOUCH_RELEASE_ON_EDGES,
  ATTR_TOUCH_START_FORCE_PREVENT_DEFAULT,
  ATTR_TOUCH_START_PREVENT_DEFAULT,
  ATTR_UNIQUE_NAV_ELEMENTS,
  ATTR_UPDATE_ON_WINDOW_RESIZE,
  ATTR_URL,
  ATTR_USER_AGENT,
  ATTR_VIRTUAL_TRANSLATE,
  ATTR_WATCH_OVERFLOW,
  ATTR_WATCH_SLIDES_PROGRESS,
  ATTR_WIDTH,
  ATTR_WRAPPER_CLASS,
} from "lib/attributes";
import { parseBoolean, parseNumber, parseString } from "../util";

export function generalConfig(el: HTMLElement) {
  return {
    allowSlideNext: parseBoolean(el, ATTR_ALLOW_SLIDE_NEXT, true),
    allowSlidePrev: parseBoolean(el, ATTR_ALLOW_SLIDE_PREV, true),
    allowTouchMove: parseBoolean(el, ATTR_ALLOW_TOUCH_MOVE, true),
    autoHeight: parseBoolean(el, ATTR_AUTO_HEIGHT, false),
    breakpointsBase: parseString(el, ATTR_BREAKPOINTS_BASE, "window"),
    centerInsufficientSlides: parseBoolean(el, ATTR_CENTER_INSUFFICIENT_SLIDES, false),
    centeredSlides: parseBoolean(el, ATTR_CENTERED_SLIDES, false),
    containerModifierClass: parseString(el, ATTR_CONTAINER_MODIFIER_CLASS, "swiper-"),
    createElements: parseBoolean(el, ATTR_CREATE_ELEMENTS, false),
    cssMode: parseBoolean(el, ATTR_CSS_MODE, false),
    direction: parseString(el, ATTR_DIRECTION, "horizontal"),
    edgeSwipeDetection: parseBoolean(el, ATTR_EDGE_SWIPE_DETECTION, false),
    edgeSwipeThreshold: parseNumber(el, ATTR_EDGE_SWIPE_THRESHOLD, 20),
    effect: parseString(el, ATTR_EFFECT, "slide"),
    enabled: parseBoolean(el, ATTR_ENABLED, true),
    eventsPrefix: parseString(el, ATTR_EVENTS_PREFIX, "swiper"),
    focusableElements: parseString(
      el,
      ATTR_FOCUSABLE_ELEMENTS,
      "input, select, option, textarea, button, video, label",
    ),
    followFinger: parseBoolean(el, ATTR_FOLLOW_FINGER, true),
    freeMode: {
      enabled: parseBoolean(el, ATTR_FREE_MODE_ENABLED, false),
      sticky: parseBoolean(el, ATTR_FREE_MODE_STICKY, false),
    },
    grabCursor: parseBoolean(el, ATTR_GRAB_CURSOR, false),
    //hashNavigation: null,
    height: parseNumber(el, ATTR_HEIGHT),
    //history: null,
    init: parseBoolean(el, ATTR_INIT, true),
    initialSlide: parseNumber(el, ATTR_INITIAL_SLIDE, 0),
    //injectStyles: null, // not needed
    //injectStylesUrls: null, // not needed
    lazyPreloadPrevNext: parseNumber(el, ATTR_LAZY_PRELOAD_PREV_NEXT, 0),
    lazyPreloaderClass: parseString(el, ATTR_LAZY_PRELOADER_CLASS, "swiper-lazy-preloader"),
    longSwipes: parseBoolean(el, ATTR_LONG_SWIPES, true), // no effect
    longSwipesMs: parseNumber(el, ATTR_LONG_SWIPES_MS, 300), // no effect
    longSwipesRatio: parseNumber(el, ATTR_LONG_SWIPES_RATIO, 0.5), // no effect
    loop: parseBoolean(el, ATTR_LOOP, false),
    loopAddBlankSlides: parseBoolean(el, ATTR_LOOP_ADD_BLANK_SLIDES, true),
    loopAdditionalSlides: parseNumber(el, ATTR_LOOP_ADD_ADDITIONAL_SLIDES, 0),
    loopPreventsSliding: parseBoolean(el, ATTR_LOOP_PREVENTS_SLIDING, true),
    maxBackfaceHiddenSlides: parseNumber(el, ATTR_MAX_BACKFACE_HIDDEN_SLIDES, 10),
    //modules: null, // NOTE probably not needed
    //mouseWheel: null //REVIEW - might be needed
    //navigation: null // NOTE - this is handled in navigationConfig
    nested: parseBoolean(el, ATTR_NESTED, false),
    noSwiping: parseBoolean(el, ATTR_NO_SWIPING, true),
    noSwipingClass: parseString(el, ATTR_NO_SWIPING_CLASS, "swiper-no-swiping"),
    noSwipingSelector: parseString(el, ATTR_NO_SWIPING_SELECTOR),
    normalizeSlideIndex: parseBoolean(el, ATTR_NORMALIZE_SLIDE_INDEX, true),
    observeParents: parseBoolean(el, ATTR_OBSERVE_SLIDE_PARENTS, false),
    observeSlideChildren: parseBoolean(el, ATTR_OBSERVE_SLIDE_CHILDREN, false),
    observer: parseBoolean(el, ATTR_OBSERVER, false),
    //on: null, // NOTE not needed
    //onAny: null, // NOTE not needed
    oneWayMovement: parseBoolean(el, ATTR_ONE_WAY_MOVEMENT, false),
    //parallax: null, //REVIEW - look at this
    passiveListeners: parseBoolean(el, ATTR_PASSIVE_LISTENERS, true),
    preventClicks: parseBoolean(el, ATTR_PREVENT_CLICKS, true),
    preventClicksPropagation: parseBoolean(el, ATTR_PREVENT_CLICKS_PROPAGATION, true),
    preventInteractionOnTransition: parseBoolean(el, ATTR_PREVENT_INTERACTION_ON_TRANSITION, false),
    resistance: parseBoolean(el, ATTR_RESISTANCE, true),
    resistanceRatio: parseNumber(el, ATTR_RESISTANCE_RATIO, 0.85),
    resizeObserver: parseBoolean(el, ATTR_RESIZE_OBSERVER, true),
    rewind: parseBoolean(el, ATTR_REWIND, false),
    roundLengths: parseBoolean(el, ATTR_ROUND_LENGTHS, false),
    runCallbacksOnInit: parseBoolean(el, ATTR_RUN_CALLBACKS_ON_INIT, true),
    setWrapperSize: parseBoolean(el, ATTR_SET_WRAPPER_SIZE, false),
    shortSwipes: parseBoolean(el, ATTR_SHORT_SWIPES, true),
    simulateTouch: parseBoolean(el, ATTR_SIMULATE_TOUCH, true),
    slideActiveClass: parseString(el, ATTR_SLIDE_ACTIVE_CLASS, "swiper-slide-active"),
    slideBlankClass: parseString(el, ATTR_SLIDE_BLANK_CLASS, "swiper-slide-blank"),
    slideClass: parseString(el, ATTR_SLIDE_CLASS, "swiper-slide"),
    slideFullyVisibleClass: parseString(el, ATTR_SLIDE_FULLY_VISIBLE_CLASS, "swiper-slide-fully-visible"),
    slideNextClass: parseString(el, ATTR_SLIDE_NEXT_CLASS, "swiper-slide-next"),
    slidePrevClass: parseString(el, ATTR_SLIDE_PREV_CLASS, "swiper-slide-prev"),
    slideToClickedSlide: parseBoolean(el, ATTR_SLIDE_TO_CLICKED_SLIDE, false),
    slideVisibleClass: parseString(el, ATTR_SLIDE_VISIBLE_CLASS, "swiper-slide-visible"),
    slidesOffsetAfter: parseNumber(el, ATTR_SLIDES_OFFSET_AFTER, 0),
    slidesOffsetBefore: parseNumber(el, ATTR_SLIDES_OFFSET_BEFORE, 0),
    slidesPerGroup: parseNumber(el, ATTR_SLIDES_PER_GROUP, 1),
    slidesPerGroupAuto: parseBoolean(el, ATTR_SLIDES_PER_GROUP_AUTO, false),
    slidesPerGroupSkip: parseNumber(el, ATTR_SLIDES_PER_GROUP_SKIP, 0),
    slidesPerView: parseNumber(el, ATTR_SLIDES_PER_VIEW, 1),
    spaceBetween: parseNumber(el, ATTR_SPACE_BETWEEN, 0),
    speed: parseNumber(el, ATTR_SPEED, 300),
    swipeHandler: parseString(el, ATTR_SWIPE_HANDLER),
    swiperElementNodeName: parseString(el, ATTR_SWIPER_ELEMENT_NODE_NAME, "SWIPER-CONTAINER"),
    threshold: parseNumber(el, ATTR_THRESHOLD, 5),
    touchAngle: parseNumber(el, ATTR_TOUCH_ANGLE, 45),
    touchEventsTarget: parseString(el, ATTR_TOUCH_EVENTS_TARGET, "wrapper"),
    touchMoveStopPropagation: parseBoolean(el, ATTR_TOUCH_MOVE_STOP_PROPAGATION, false),
    touchRatio: parseNumber(el, ATTR_TOUCH_RATIO, 1),
    touchReleaseOnEdges: parseBoolean(el, ATTR_TOUCH_RELEASE_ON_EDGES, false),
    touchStartForcePreventDefault: parseBoolean(el, ATTR_TOUCH_START_FORCE_PREVENT_DEFAULT, false),
    touchStartPreventDefault: parseBoolean(el, ATTR_TOUCH_START_PREVENT_DEFAULT, true),
    uniqueNavElements: parseBoolean(el, ATTR_UNIQUE_NAV_ELEMENTS, true),
    updateOnWindowResize: parseBoolean(el, ATTR_UPDATE_ON_WINDOW_RESIZE, true),
    url: parseString(el, ATTR_URL),
    userAgent: parseString(el, ATTR_USER_AGENT),
    //virtual: null, //NOTE - not implemented
    virtualTranslate: parseBoolean(el, ATTR_VIRTUAL_TRANSLATE, false),
    watchOverflow: parseBoolean(el, ATTR_WATCH_OVERFLOW, true),
    watchSlidesProgress: parseBoolean(el, ATTR_WATCH_SLIDES_PROGRESS, false),
    width: parseNumber(el, ATTR_WIDTH),
    wrapperClass: parseString(el, ATTR_WRAPPER_CLASS, "swiper-wrapper"),
    //zoom: null, //NOTE - not implemented
  };
}
