import {
  ATTR_ALLOW_SLIDE_NEXT,
  ATTR_ALLOW_SLIDE_PREV,
  ATTR_ALLOW_TOUCH_MOVE,
  ATTR_AUTO_HEIGHT,
  ATTR_BREAKPOINTS_BASE,
  ATTR_CENTER_INSUFFICIENT_SLIDES,
  ATTR_CENTERED_SLIDES,
  ATTR_CONTAINER_MODIFIER_CLASS,
  ATTR_CREATE_ELEMENTS,
  ATTR_CSS_MODE,
  ATTR_DIRECTION,
  ATTR_EDGE_SWIPE_DETECTION,
  ATTR_EDGE_SWIPE_THRESHOLD,
  ATTR_EFFECT,
  ATTR_ENABLED,
  ATTR_EVENTS_PREFIX,
  ATTR_FOCUSABLE_ELEMENTS,
  ATTR_FOLLOW_FINGER,
  ATTR_FREE_MODE_ENABLED,
  ATTR_FREE_MODE_STICKY,
  ATTR_SLIDE_FULLY_VISIBLE_CLASS,
  ATTR_GRAB_CURSOR,
  ATTR_HEIGHT,
  ATTR_INIT,
  ATTR_INITIAL_SLIDE,
  ATTR_LAZY_PRELOAD_PREV_NEXT,
  ATTR_LAZY_PRELOADER_CLASS,
  ATTR_LONG_SWIPES,
  ATTR_LONG_SWIPES_MS,
  ATTR_LONG_SWIPES_RATIO,
  ATTR_LOOP,
  ATTR_LOOP_ADD_ADDITIONAL_SLIDES,
  ATTR_LOOP_ADD_BLANK_SLIDES,
  ATTR_LOOP_PREVENTS_SLIDING,
  ATTR_MAX_BACKFACE_HIDDEN_SLIDES,
  ATTR_NESTED,
  ATTR_NO_SWIPING,
  ATTR_NO_SWIPING_CLASS,
  ATTR_NO_SWIPING_SELECTOR,
  ATTR_NORMALIZE_SLIDE_INDEX,
  ATTR_OBSERVE_SLIDE_CHILDREN,
  ATTR_OBSERVE_SLIDE_PARENTS,
  ATTR_OBSERVER,
  ATTR_ONE_WAY_MOVEMENT,
  ATTR_PASSIVE_LISTENERS,
  ATTR_PREVENT_CLICKS,
  ATTR_PREVENT_CLICKS_PROPAGATION,
  ATTR_PREVENT_INTERACTION_ON_TRANSITION,
  ATTR_RESISTANCE,
  ATTR_RESISTANCE_RATIO,
  ATTR_RESIZE_OBSERVER,
  ATTR_REWIND,
  ATTR_ROUND_LENGTHS,
  ATTR_RUN_CALLBACKS_ON_INIT,
  ATTR_SET_WRAPPER_SIZE,
  ATTR_SHORT_SWIPES,
  ATTR_SIMULATE_TOUCH,
  ATTR_SLIDE_ACTIVE_CLASS,
  ATTR_SLIDE_BLANK_CLASS,
  ATTR_SLIDE_CLASS,
  ATTR_SLIDE_NEXT_CLASS,
  ATTR_SLIDE_PREV_CLASS,
  ATTR_SLIDE_TO_CLICKED_SLIDE,
  ATTR_SLIDE_VISIBLE_CLASS,
  ATTR_SLIDES_OFFSET_AFTER,
  ATTR_SLIDES_OFFSET_BEFORE,
  ATTR_SLIDES_PER_GROUP,
  ATTR_SLIDES_PER_GROUP_AUTO,
  ATTR_SLIDES_PER_GROUP_SKIP,
  ATTR_SLIDES_PER_VIEW,
  ATTR_SPACE_BETWEEN,
  ATTR_SPEED,
  ATTR_SWIPE_HANDLER,
  ATTR_SWIPER_ELEMENT_NODE_NAME,
  ATTR_THRESHOLD,
  ATTR_TOUCH_ANGLE,
  ATTR_TOUCH_EVENTS_TARGET,
  ATTR_TOUCH_MOVE_STOP_PROPAGATION,
  ATTR_TOUCH_RATIO,
  ATTR_TOUCH_RELEASE_ON_EDGES,
  ATTR_TOUCH_START_FORCE_PREVENT_DEFAULT,
  ATTR_TOUCH_START_PREVENT_DEFAULT,
  ATTR_UNIQUE_NAV_ELEMENTS,
  ATTR_UPDATE_ON_WINDOW_RESIZE,
  ATTR_URL,
  ATTR_USER_AGENT,
  ATTR_VIRTUAL_TRANSLATE,
  ATTR_WATCH_OVERFLOW,
  ATTR_WATCH_SLIDES_PROGRESS,
  ATTR_WIDTH,
  ATTR_WRAPPER_CLASS,
} from "lib/attributes";
import { parseAttr } from "../util";

export function generalConfig(el: HTMLElement) {
  return {
    allowSlideNext: parseAttr(el, ATTR_ALLOW_SLIDE_NEXT, true),
    allowSlidePrev: parseAttr(el, ATTR_ALLOW_SLIDE_PREV, true),
    allowTouchMove: parseAttr(el, ATTR_ALLOW_TOUCH_MOVE, true),
    autoHeight: parseAttr(el, ATTR_AUTO_HEIGHT, false),
    breakpointsBase: parseAttr(el, ATTR_BREAKPOINTS_BASE, "window"),
    centerInsufficientSlides: parseAttr(el, ATTR_CENTER_INSUFFICIENT_SLIDES, false),
    centeredSlides: parseAttr(el, ATTR_CENTERED_SLIDES, false),
    containerModifierClass: parseAttr(el, ATTR_CONTAINER_MODIFIER_CLASS, "swiper-"),
    createElements: parseAttr(el, ATTR_CREATE_ELEMENTS, false),
    cssMode: parseAttr(el, ATTR_CSS_MODE, false),
    direction: parseAttr(el, ATTR_DIRECTION, "horizontal"),
    edgeSwipeDetection: parseAttr(el, ATTR_EDGE_SWIPE_DETECTION, false),
    edgeSwipeThreshold: parseAttr(el, ATTR_EDGE_SWIPE_THRESHOLD, 20),
    effect: parseAttr(el, ATTR_EFFECT, "slide"),
    enabled: parseAttr(el, ATTR_ENABLED, true),
    eventsPrefix: parseAttr(el, ATTR_EVENTS_PREFIX, "swiper"),
    focusableElements: parseAttr(el, ATTR_FOCUSABLE_ELEMENTS, "input, select, option, textarea, button, video, label"),
    followFinger: parseAttr(el, ATTR_FOLLOW_FINGER, true),
    freeMode: {
      enabled: parseAttr(el, ATTR_FREE_MODE_ENABLED, false),
      sticky: parseAttr(el, ATTR_FREE_MODE_STICKY, false),
    },
    grabCursor: parseAttr(el, ATTR_GRAB_CURSOR, false),
    //hashNavigation: null,
    height: parseAttr(el, ATTR_HEIGHT, null),
    //history: null,
    init: parseAttr(el, ATTR_INIT, true),
    initialSlide: parseAttr(el, ATTR_INITIAL_SLIDE, 0),
    //injectStyles: null, // not needed
    //injectStylesUrls: null, // not needed
    lazyPreloadPrevNext: parseAttr(el, ATTR_LAZY_PRELOAD_PREV_NEXT, 0),
    lazyPreloaderClass: parseAttr(el, ATTR_LAZY_PRELOADER_CLASS, "swiper-lazy-preloader"),
    longSwipes: parseAttr(el, ATTR_LONG_SWIPES, true), // no effect
    longSwipesMs: parseAttr(el, ATTR_LONG_SWIPES_MS, 300), // no effect
    longSwipesRatio: parseAttr(el, ATTR_LONG_SWIPES_RATIO, 0.5), // no effect
    loop: parseAttr(el, ATTR_LOOP, false),
    loopAddBlankSlides: parseAttr(el, ATTR_LOOP_ADD_BLANK_SLIDES, true),
    loopAdditionalSlides: parseAttr(el, ATTR_LOOP_ADD_ADDITIONAL_SLIDES, 0),
    loopPreventsSliding: parseAttr(el, ATTR_LOOP_PREVENTS_SLIDING, true),
    maxBackfaceHiddenSlides: parseAttr(el, ATTR_MAX_BACKFACE_HIDDEN_SLIDES, 10),
    //modules: null, // NOTE probably not needed
    //mouseWheel: null //REVIEW - might be needed
    //navigation: null // NOTE - this is handled in navigationConfig
    nested: parseAttr(el, ATTR_NESTED, false),
    noSwiping: parseAttr(el, ATTR_NO_SWIPING, true),
    noSwipingClass: parseAttr(el, ATTR_NO_SWIPING_CLASS, "swiper-no-swiping"),
    noSwipingSelector: parseAttr(el, ATTR_NO_SWIPING_SELECTOR, null),
    normalizeSlideIndex: parseAttr(el, ATTR_NORMALIZE_SLIDE_INDEX, true),
    observeParents: parseAttr(el, ATTR_OBSERVE_SLIDE_PARENTS, false),
    observeSlideChildren: parseAttr(el, ATTR_OBSERVE_SLIDE_CHILDREN, false),
    observer: parseAttr(el, ATTR_OBSERVER, false),
    //on: null, // NOTE not needed
    //onAny: null, // NOTE not needed
    oneWayMovement: parseAttr(el, ATTR_ONE_WAY_MOVEMENT, false),
    //parallax: null, //REVIEW - look at this
    passiveListeners: parseAttr(el, ATTR_PASSIVE_LISTENERS, true),
    preventClicks: parseAttr(el, ATTR_PREVENT_CLICKS, true),
    preventClicksPropagation: parseAttr(el, ATTR_PREVENT_CLICKS_PROPAGATION, true),
    preventInteractionOnTransition: parseAttr(el, ATTR_PREVENT_INTERACTION_ON_TRANSITION, false),
    resistance: parseAttr(el, ATTR_RESISTANCE, true),
    resistanceRatio: parseAttr(el, ATTR_RESISTANCE_RATIO, 0.85),
    resizeObserver: parseAttr(el, ATTR_RESIZE_OBSERVER, true),
    rewind: parseAttr(el, ATTR_REWIND, false),
    roundLengths: parseAttr(el, ATTR_ROUND_LENGTHS, false),
    runCallbacksOnInit: parseAttr(el, ATTR_RUN_CALLBACKS_ON_INIT, true),
    setWrapperSize: parseAttr(el, ATTR_SET_WRAPPER_SIZE, false),
    shortSwipes: parseAttr(el, ATTR_SHORT_SWIPES, true),
    simulateTouch: parseAttr(el, ATTR_SIMULATE_TOUCH, true),
    slideActiveClass: parseAttr(el, ATTR_SLIDE_ACTIVE_CLASS, "swiper-slide-active"),
    slideBlankClass: parseAttr(el, ATTR_SLIDE_BLANK_CLASS, "swiper-slide-blank"),
    slideClass: parseAttr(el, ATTR_SLIDE_CLASS, "swiper-slide"),
    slideFullyVisibleClass: parseAttr(el, ATTR_SLIDE_FULLY_VISIBLE_CLASS, "swiper-slide-fully-visible"),
    slideNextClass: parseAttr(el, ATTR_SLIDE_NEXT_CLASS, "swiper-slide-next"),
    slidePrevClass: parseAttr(el, ATTR_SLIDE_PREV_CLASS, "swiper-slide-prev"),
    slideToClickedSlide: parseAttr(el, ATTR_SLIDE_TO_CLICKED_SLIDE, false),
    slideVisibleClass: parseAttr(el, ATTR_SLIDE_VISIBLE_CLASS, "swiper-slide-visible"),
    slidesOffsetAfter: parseAttr(el, ATTR_SLIDES_OFFSET_AFTER, 0),
    slidesOffsetBefore: parseAttr(el, ATTR_SLIDES_OFFSET_BEFORE, 0),
    slidesPerGroup: parseAttr(el, ATTR_SLIDES_PER_GROUP, 1),
    slidesPerGroupAuto: parseAttr(el, ATTR_SLIDES_PER_GROUP_AUTO, false),
    slidesPerGroupSkip: parseAttr(el, ATTR_SLIDES_PER_GROUP_SKIP, 0),
    slidesPerView: parseAttr(el, ATTR_SLIDES_PER_VIEW, "1"),
    spaceBetween: parseAttr(el, ATTR_SPACE_BETWEEN, 0),
    speed: parseAttr(el, ATTR_SPEED, 300),
    swipeHandler: parseAttr(el, ATTR_SWIPE_HANDLER, null),
    swiperElementNodeName: parseAttr(el, ATTR_SWIPER_ELEMENT_NODE_NAME, "SWIPER-CONTAINER"),
    threshold: parseAttr(el, ATTR_THRESHOLD, 5),
    touchAngle: parseAttr(el, ATTR_TOUCH_ANGLE, 45),
    touchEventsTarget: parseAttr(el, ATTR_TOUCH_EVENTS_TARGET, "wrapper"),
    touchMoveStopPropagation: parseAttr(el, ATTR_TOUCH_MOVE_STOP_PROPAGATION, false),
    touchRatio: parseAttr(el, ATTR_TOUCH_RATIO, 1),
    touchReleaseOnEdges: parseAttr(el, ATTR_TOUCH_RELEASE_ON_EDGES, false),
    touchStartForcePreventDefault: parseAttr(el, ATTR_TOUCH_START_FORCE_PREVENT_DEFAULT, false),
    touchStartPreventDefault: parseAttr(el, ATTR_TOUCH_START_PREVENT_DEFAULT, true),
    uniqueNavElements: parseAttr(el, ATTR_UNIQUE_NAV_ELEMENTS, true),
    updateOnWindowResize: parseAttr(el, ATTR_UPDATE_ON_WINDOW_RESIZE, true),
    url: parseAttr(el, ATTR_URL, "null"),
    userAgent: parseAttr(el, ATTR_USER_AGENT, "null"),
    //virtual: null, //NOTE - not implemented
    virtualTranslate: parseAttr(el, ATTR_VIRTUAL_TRANSLATE, false),
    watchOverflow: parseAttr(el, ATTR_WATCH_OVERFLOW, true),
    watchSlidesProgress: parseAttr(el, ATTR_WATCH_SLIDES_PROGRESS, false),
    width: parseAttr(el, ATTR_WIDTH, null),
    wrapperClass: parseAttr(el, ATTR_WRAPPER_CLASS, "swiper-wrapper"),
    //zoom: null, //NOTE - not implemented
  };
}
