import { parseAttr } from '../util';

export function generalConfig($this: JQuery<HTMLElement>) {
  return {
    a11y: {
      prevSlideMessage: parseAttr($this, 'a11y-prev-message', 'Previous Slide'),
      nextSlideMessage: parseAttr($this, 'a11y-next-message', 'Next Slide'),
    },
    allowSlideNext: parseAttr($this, 'allow-slide-next', true),
    allowSlidePrev: parseAttr($this, 'allow-slide-prev', true),
    allowTouchMove: parseAttr($this, 'allow-touch-move', true),
    autoHeight: parseAttr($this, 'auto-height', false),
    breakpointsBase: parseAttr($this, 'breakpoints-base', 'window'),
    centerInsufficientSlides: parseAttr(
      $this,
      'center-insufficient-slides',
      false,
    ),
    centeredSlides: parseAttr($this, 'centered-slides', false),
    containerModifierClass: parseAttr(
      $this,
      'container-modifier-class',
      'swiper-',
    ),
    createElements: parseAttr($this, 'create-elements', false),
    cssMode: parseAttr($this, 'css-mode', false),
    direction: parseAttr($this, 'direction', 'horizontal'),
    edgeSwipeDetection: parseAttr($this, 'edge-swipe-detection', false),
    edgeSwipeThreshold: parseAttr($this, 'edge-swipe-threshold', 20),
    effect: parseAttr($this, 'effect', 'slide'),
    enabled: parseAttr($this, 'enabled', true),
    eventsPrefix: parseAttr($this, 'events-prefix', 'swiper'),
    focusableElements: parseAttr(
      $this,
      'focusable-elements',
      'input, select, option, textarea, button, video, label',
    ),
    followFinger: parseAttr($this, 'follow-finger', true),
    freeMode: {
      enabled: parseAttr($this, 'free-mode-enabled', false),
      sticky: parseAttr($this, 'free-mode-sticky', false),
    },
    grabCursor: parseAttr($this, 'grab-cursor', false),
    //hashNavigation: null,
    height: parseAttr($this, 'height', null),
    //history: null,
    init: parseAttr($this, 'init', true),
    initialSlide: parseAttr($this, 'initial-slide', 0),
    //injectStyles: null, // not needed
    //injectStylesUrls: null, // not needed
    lazyPreloadPrevNext: parseAttr($this, 'lazy-preload-prev-next', 0),
    lazyPreloaderClass: parseAttr(
      $this,
      'lazy-preloader-class',
      'swiper-lazy-preloader',
    ),
    longSwipes: parseAttr($this, 'long-swipes', true), // no effect
    longSwipesMs: parseAttr($this, 'long-swipes-ms', 300), // no effect
    longSwipesRatio: parseAttr($this, 'long-swipes-ratio', 0.5), // no effect
    loop: parseAttr($this, 'loop-mode', false),
    loopAddBlankSlides: parseAttr($this, 'loop-add-blank-slides', true),
    loopAdditionalSlides: parseAttr($this, 'loop-additional-slides', 0),
    loopPreventsSliding: parseAttr($this, 'loop-prevents-sliding', true),
    maxBackfaceHiddenSlides: parseAttr($this, 'max-backface-hidden-slides', 10),
    //modules: null, // take a look at this
    //mouseWheel: null,
    //navigation: null,
    nested: parseAttr($this, 'nested', false),
    noSwiping: parseAttr($this, 'no-swiping', true),
    noSwipingClass: parseAttr($this, 'no-swiping-class', 'swiper-no-swiping'),
    noSwipingSelector: parseAttr($this, 'no-swiping-selector', null),
    normalizeSlideIndex: parseAttr($this, 'normalize-slide-index', true),
    observeParents: parseAttr($this, 'observe-parents', false),
    observeSlideChildren: parseAttr($this, 'observe-slide-children', false),
    //observer: null,
    //on: null,
    //onAny: null,
    oneWayMovement: parseAttr($this, 'data-one-way-movement', false),
    //parallax: null,
    passiveListeners: parseAttr($this, 'passive-listeners', true),
    preventClicks: parseAttr($this, 'prevent-clicks', true),
    preventClicksPropagation: parseAttr(
      $this,
      'prevent-clicks-propagation',
      true,
    ),
    preventInteractionOnTransition: parseAttr(
      $this,
      'prevent-interaction-on-transition',
      false,
    ),
    resistance: parseAttr($this, 'resistance', true),
    resistanceRatio: parseAttr($this, 'resistance-ratio', 0.85),
    resizeObserver: parseAttr($this, 'resize-observer', true),
    rewind: parseAttr($this, 'rewind', false),
    roundLengths: parseAttr($this, 'round-lengths', false),
    runCallbacksOnInit: parseAttr($this, 'run-callbacks-on-init', true),
    // setWrapperSize: getAttr($this, 'set-wrapper-size', false),
    shortSwipes: parseAttr($this, 'short-swipes', true),
    simulateTouch: parseAttr($this, 'simulate-touch', true),
    slideActiveClass: parseAttr(
      $this,
      'slide-active-class',
      'swiper-slide-active',
    ),
    slideBlankClass: parseAttr(
      $this,
      'slide-blank-class',
      'swiper-slide-blank',
    ),
    slideClass: parseAttr($this, 'slide-class', 'swiper-slide'),
    slideFullyVisibleClass: parseAttr(
      $this,
      'slide-fully-visible-class',
      'swiper-slide-fully-visible',
    ),
    slideNextClass: parseAttr($this, 'slide-next-class', 'swiper-slide-next'),
    slidePrevClass: parseAttr($this, 'slide-prev-class', 'swiper-slide-prev'),
    slideToClickedSlide: parseAttr($this, 'slide-to-clicked-slide', false),
    slideVisibleClass: parseAttr(
      $this,
      'slide-visible-class',
      'swiper-slide-visible',
    ),
    slidesOffsetAfter: parseAttr($this, 'slides-offset-after', 0),
    slidesOffsetBefore: parseAttr($this, 'slides-offset-before', 0),
    slidesPerGroup: parseAttr($this, 'slides-per-group', 1),
    slidesPerGroupAuto: parseAttr($this, 'slides-per-group-auto', false),
    slidesPerGroupSkip: parseAttr($this, 'slides-per-group-skip', 0),
    slidesPerView: parseAttr($this, 'slides-per-view', '1'),
    spaceBetween: parseAttr($this, 'space-between', 0),
    speed: parseAttr($this, 'speed', 300),
    // swipeHandler: getAttr($this, "swipe-handler", null),
    swiperElementNodeName: parseAttr(
      $this,
      'swiper-element-node-name',
      'SWIPER-CONTAINER',
    ),
    threshold: parseAttr($this, 'threshold', 5),
    touchAngle: parseAttr($this, 'touch-angle', 45),
    touchEventsTarget: parseAttr($this, 'touch-events-target', 'wrapper'),
    touchMoveStopPropagation: parseAttr(
      $this,
      'touch-move-stop-propagation',
      false,
    ),
    touchRatio: parseAttr($this, 'touch-ratio', 1),
    touchReleaseOnEdges: parseAttr($this, 'touch-release-on-edges', false),
    touchStartForcePreventDefault: parseAttr(
      $this,
      'touch-start-force-prevent-default',
      false,
    ),
    touchStartPreventDefault: parseAttr(
      $this,
      'touch-start-prevent-default',
      true,
    ),
    uniqueNavElements: parseAttr($this, 'unique-nav-elements', true),
    updateOnWindowResize: parseAttr($this, 'update-on-window-resize', true),
    //url: getAttr($this, "url", "null"),
    //userAgent: getAttr($this, "user-agent", "null"),
    //virtual: null,
    virtualTranslate: parseAttr($this, 'virtual-translate', false),
    watchOverflow: parseAttr($this, 'watch-overflow', true),
    watchSlidesProgress: parseAttr($this, 'watch-slides-progress', false),
    width: parseAttr($this, 'width', null),
    wrapperClass: parseAttr($this, 'wrapper-class', 'swiper-wrapper'),
    //zoom: null,
  };
}
